# Ingress for LLM Engine
# This template creates an ingress resource to expose the Ray Serve application
# Note: VS Code YAML parser may show errors due to Helm template syntax

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host | default "llm-engine.local" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-head-svc
            port:
              number: 8000
{{- end }}